### PR TITLE
File with MEH comments on each hit

### PR DESCRIPTION
**Pull request by TomConlin**
As time allows I am looking at each hit and making comments.

### CODE REVIEW

**Comment by dnahotline** [comment]
tom where is the bet place to leave comments on each hit?

**Comment by TomConlin** [comment]
I would recommend where ever you feel comfortable and efficient . 
If that is a local spread sheet you could just check it in once in a while . 
Or try the g doc route if you wanted to share w/ other bio folks . 
I do not think you need feel confined to  a particular technology
and we should not have any legal concerns as everything is already open

**Comment by dnahotline** [comment]
Ok thx

**Comment by dnahotline** [comment]
I've shared an item with you:

FA_and_ontology_hackathon_presentation_25may2017.pptx
https://drive.google.com/file/d/0B7Omkk56O8TganlUS1JHaXJ2QlU/view?usp=sharing&ts=5a9f345b

It's not an attachment – it's stored online. To open this item, just click  
the link above.

**Pull request merged**
